apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: python-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ВАШ_НИК/k8s-python-app
  ref:
    branch: main
  secretRef:
    name: github-auth
